#!/bin/bash

RAWBLOCKSIZE=6404096
HEADERSIZE=32768

infile="$1"
offset="${2:-0}"
length="${3:-$HEADERSIZE}"

filesize=$(stat -c "%s" "$infile")
let start=filesize-RAWBLOCKSIZE-1+offset

dd if="$infile" iflag=skip_bytes,count_bytes \
                skip=$start count=$length 2>/dev/null | hexdump -C
